FPTWebApplication/Models/Trainee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FPTWebApplication.Models
{
    public class Trainee
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public DateTime BDay { get; set; }
        public string Course { get; set; }

    }
}

FPTWebApplication/Controllers/TraineesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FPTWebApplication.Models;

namespace FPTWebApplication.Controllers
{
    public class TraineesController : Controller
    {
        private ApplicationDbContext _context;
        private List<Trainee> _trainees;
        public TraineesController()
        {

            _context = new ApplicationDbContext();
        }
        // GET: Trainees
        public ActionResult Index()
        {
            var trainees = _context.Trainees.ToList();
            return View(trainees);
        }

        public ActionResult Details(int id)
        {
            if (id == null) return HttpNotFound();
            var trainee = _context.Trainees.SingleOrDefault(t => t.Id == id);
            if (trainee == null) return HttpNotFound();
            return View(trainee);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null) return HttpNotFound();
            var trainee = _context.Trainees.SingleOrDefault(t => t.Id == id);
            if (trainee == null) return HttpNotFound();
            _context.Trainees.Remove(trainee);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Trainee trainee)
        {
            var newTrainee = new Trainee()
            {
                FullName = trainee.FullName,
                Gender = trainee.Gender,
                BDay = trainee.BDay,
                Course = trainee.Course,
            };

            _context.Trainees.Add(newTrainee);
            _context.SaveChanges();
        
            return RedirectToAction("Index");
        }

        public ActionResult Edit()
        {
            return View();
        }
    }
}

FPTWebApplication/Views/Trainees/Create.cshtml
@model FPTWebApplication.Models.Trainee
@{
    ViewBag.Title = "Create";
}

<h2>Create new Trainee</h2>

@using (Html.BeginForm("Create", "Trainees", FormMethod.Post))
{
    <div class="form-group">
        <label>Full Name</label>
        @Html.TextBoxFor(m => m.FullName, new { @class = "form-control", @placeholder = "Enter full name" })
    </div>
    <div class="form-group">
        <label>Gender</label>
        @Html.TextBoxFor(m => m.Gender, new { @class = "form-control", @placeholder = "Enter gender" })
    </div>
    <div class="form-group">
        <label>Birthday</label>
        @Html.TextBoxFor(m => m.BDay, new {@type = "date", @class = "form-control", @placeholder = "Enter birthday" })
    </div>
    <div class="form-group">
        <label>Course</label>
        @Html.TextBoxFor(m => m.Course, new { @class = "form-control", @placeholder = "Enter course" })
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
}

FPTWebApplication/Views/Trainees/Details.cshtml
@model FPTWebApplication.Models.Trainee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div class="form-group">
    @Html.ActionLink("Back to Trainee",
        "Index",
        "Trainees",
        null,
        new { @class = "btn btn-primary" })
</div>

<div class="panel panel-primary">
    <div class="panel-heading">Information of Trainee</div>
    <div class="panel-body">
        <p>Full Name: @Model.FullName</p>
        <p>Gender: @Model.Gender</p>
        <p>Birthday: @Model.BDay</p>
        <p>Course: @Model.Course</p>
    </div>
</div>

FPTWebApplication/Views/Trainees/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Trainee</h2>

<form>
    <div class="form-group">
        <label>Full Name</label>
        <input type="text" class="form-control" placeholder="Enter full name" />
    </div>
    <div class="form-group">
        <label>Gender</label>
        <input type="text" class="form-control" placeholder="Enter gender" />
    </div>
    <div class="form-group">
        <label>Birthday</label>
        <input type="date" class="form-control" />
    </div>
    <div class="form-group">
        <label>Course</label>
        <input type="text" class="form-control" placeholder="Enter Course" />
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Edit</button>
    </div>
</form>

FPTWebApplication/Views/Trainees/Index.cshtml
@model IEnumerable<FPTWebApplication.Models.Trainee>
@{
    ViewBag.Title = "Index";
}

<h1>Trainee</h1>
@Html.ActionLink(
    "Create new Trainee", 
    "Create", 
    "Trainees",null,
    new { @class = "btn btn-primary" }
    )

<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">#ID</th>
            <th scope="col">Full Name</th>
            <th scope="col">Gender</th>
            <th scope="col">Birth Day</th>
            <th scope="col">Course</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var trainee in Model)
        {
            <tr>
                <th scope="row">@trainee.Id</th>
                <td>@trainee.FullName</td>
                <td>@trainee.Gender</td>
                <td>@trainee.BDay</td>
                <td>@trainee.Course</td>
                <td>
                    @Html.ActionLink(
                   "Detail",
                   "Details",
                   "Trainees",
                   new { id = trainee.Id },
                   new { @class = "btn btn-primary" }
                   )
                    
                    @Html.ActionLink(
                  "Delete",
                  "Delete",
                  "Trainees",
                  new { id = trainee.Id },
                  new { @class = "btn btn-danger" }
                  ) 
                    <a href="#" class="btn btn-default">Edit</a>

                </td>
            </tr>
        }

    </tbody>
</table>